### PR TITLE
Quickhull: more hybridization and cleanup

### PR DESCRIPTION
**Pull request by shwestrick**
Doing more hybridization to quickhull, as suggested in #2. And, generally trying to make the code a bit cleaner.

Current status is shown at the bottom. TLDR: hybrid semihull needs more work.

The good performance at P=1 and then the sudden drop-off highlights the problem. The computation is broken into two top-level choices for the two semihulls. On P=1, both semihulls are executed on the GPU (back-to-back) and the performance is good. But with P>1, we have an extra CPU, and that CPU starts executing the hybrid semihull code. The current hybrid semihull unconditionally requires a significant amount of CPU work and therefore does not perform well on small core counts.

Screen Shot 2023-10-14 at 10 30 13 PM

### CODE REVIEW

**Comment by shwestrick** [comment]
Felt inspired after lunch and decided to implement a hybrid filter. This turned out to work well; on low core counts, the hybrid performance vs GPU is much better now (only approx 2x slower in the worst case).

The previous code had that funky performance anomaly at P=1; I intentionally removed that in this updated version.

I also tweaked some other things to encourage better hybridization, and got a small performance boost at the high core counts, too. (I think was due to better utilization of the GPU, but haven't confirmed that.)

New speedup plot below. I'm happy leaving it here.

Screenshot 2023-10-17 at 3 56 27 PM

**Comment by athas** [comment]
Can't argue with the performance, but what is the main trick here?  Is it all down to hybridizing the split?  Anyway, this looks like a pretty good benchmark now.  Complicated but ultimately fast.

(Also, Python 2, really?  Isn't it becoming unavailable on most systems these days?)

**Comment by shwestrick** [comment]
> Can't argue with the performance, but what is the main trick here? Is it all down to hybridizing the split?

Essentially, yes. If the split was not hybridized, then the minimum amount of CPU work would be the cost of splitting along one "root-to-leaf" path, i.e., `SplitCost(n) + SplitCost(n/2) + SplitCost(n/4) + ...` which comes out to `O(n)` work on the CPU, yet the total work of the benchmark is only `O(n log n)`. So, we end up with approximately `O(n log n)` GPU work and `O(n)` CPU work, which (for small CPU counts) is going to be bottlenecked by CPU performance.

> (Also, Python 2, really? Isn't it becoming unavailable on most systems these days?)

It's an old script sir, but it checks out 🤡 

But actually though, I think maybe you did some changes to this script earlier to update for Python 3? Those didn't work for me unfortunately :/ it crashed when I tried, and I wasn't sure why. So, I reverted to the old version of the script for now.

**Comment by shwestrick** [comment]
Just updated `scripts/runcmds` for Python 3 :) b504a5c839c6bcfac9a1cc98a60cae60e92f35aa

**Pull request merged**
